name: kwil-ls-oracle-tesnet
services:
  kwil-postgres-1:
    image: "kwildb/postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # persis data
    volumes:
      - type: volume
        source: data-kwil-postgres-1
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    networks:
      - kwil-network

  kwil-postgres-2:
    image: "kwildb/postgres:latest"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # persis data
    volumes:
      - type: volume
        source: data-kwil-postgres-2
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    networks:
      - kwil-network

  kwil-postgres-3:
    image: "kwildb/postgres:latest"
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # persis data
    volumes:
      - type: volume
        source: data-kwil-postgres-3
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    networks:
      - kwil-network

  kwil-node-1:
    container_name: kwil-node-1
    hostname: kwil-node-1
    build:
      context: .
      dockerfile: ./kwil.dockerfile
#      args:
#        - DEBUG_PORT=2345
    ports:
      - "8080:8080"
      - "2345:2345"
    depends_on:
      kwil-postgres-1:
        condition: service_healthy
    volumes:
      - ./examples/testnet/node1/config.toml:/root/.kwild/config.toml
      - ./examples/testnet/node1/private_key:/root/.kwild/private_key
      - ./examples/testnet/common-genesis.json:/root/.kwild/genesis.json
      - type: volume
        source: data-kwil-1
        target: /root/.kwild
        volume:
          nocopy: true
    networks:
      - kwil-network


  kwil-node-2:
    container_name: kwil-node-2
    hostname: kwil-node-2
    build:
      context: .
      dockerfile: ./kwil.dockerfile
    # Don't enable ports to enforce the use of node 1 as interface
    depends_on:
      kwil-postgres-2:
        condition: service_healthy
    volumes:
      - ./examples/testnet/node2/config.toml:/root/.kwild/config.toml
      - ./examples/testnet/node2/private_key:/root/.kwild/private_key
      - ./examples/testnet/common-genesis.json:/root/.kwild/genesis.json
      - type: volume
        source: data-kwil-2
        target: /root/.kwild
        volume:
          nocopy: true
    networks:
      - kwil-network


  kwil-node-3:
    container_name: kwil-node-3
    hostname: kwil-node-3
    build:
      context: .
      dockerfile: ./kwil.dockerfile
    # Don't enable ports to enforce the use of node 1 as interface
    depends_on:
      kwil-postgres-3:
        condition: service_healthy
    volumes:
      - ./examples/testnet/node3/config.toml:/root/.kwild/config.toml
      - ./examples/testnet/node3/private_key:/root/.kwild/private_key
      - ./examples/testnet/common-genesis.json:/root/.kwild/genesis.json
      - type: volume
        source: data-kwil-3
        target: /root/.kwild
        volume:
          nocopy: true
    networks:
      - kwil-network

  logstore-node-1:
    container_name: logstore-node-1
    hostname: logstore-node-1
    image: ghcr.io/usherlabs/logstore-node:develop
    command: [ "start-in-docker", "start" ]
    networks:
      - kwil-network
    environment:
      - PROVER_MODE=dev
      - NOTARY_URL=10.200.10.1:7047
      - EXPERIMENTAL_SOROBAN_SINK=true
      - SINK_STELLAR_WALLET_PRIVATE_KEY=SCMDRX7A7OVRPAGXLUVRNIYTWBLCS54OV7UH2TF5URSG4B4JQMUADCYU
    volumes:
      - type: bind
        source: ./examples/testnet/node1/logstore-config.json
        target: /home/node/.logstore/config/default.json
        read_only: true
      - type: volume
        source: data-logstore-1
        target: /home/node/.logstore/

  logstore-node-2:
    container_name: logstore-node-2
    hostname: logstore-node-2
    image: ghcr.io/usherlabs/logstore-node:develop
    command: [ "start-in-docker", "start" ]
    networks:
      - kwil-network
    environment:
      - PROVER_MODE=dev
      - NOTARY_URL=10.200.10.1:7047
      - EXPERIMENTAL_SOROBAN_SINK=true
      - SINK_STELLAR_WALLET_PRIVATE_KEY=SCMDRX7A7OVRPAGXLUVRNIYTWBLCS54OV7UH2TF5URSG4B4JQMUADCYU
    volumes:
      - type: bind
        source: ./examples/testnet/node2/logstore-config.json
        target: /home/node/.logstore/config/default.json
        read_only: true
      - type: volume
        source: data-logstore-2
        target: /home/node/.logstore/

  logstore-node-3:
    container_name: logstore-node-3
    hostname: logstore-node-3
    image: ghcr.io/usherlabs/logstore-node:develop
    command: [ "start-in-docker", "start" ]
    networks:
      - kwil-network
    environment:
      - PROVER_MODE=dev
      - NOTARY_URL=10.200.10.1:7047
      - EXPERIMENTAL_SOROBAN_SINK=true
      - SINK_STELLAR_WALLET_PRIVATE_KEY=SCMDRX7A7OVRPAGXLUVRNIYTWBLCS54OV7UH2TF5URSG4B4JQMUADCYU
    volumes:
      - type: bind
        source: ./examples/testnet/node3/logstore-config.json
        target: /home/node/.logstore/config/default.json
        read_only: true
      - type: volume
        source: data-logstore-3
        target: /home/node/.logstore/



networks:
  kwil-network:
    driver: bridge

volumes:
  data-kwil-1:
  data-kwil-2:
  data-kwil-3:
  data-kwil-postgres-1:
  data-kwil-postgres-2:
  data-kwil-postgres-3:
  data-logstore-1:
  data-logstore-2:
  data-logstore-3:
