name: kwil-ls-oracle
services:
  kwil-postgres:
    image: "kwildb/postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # persis data
    volumes:
      - type: volume
        source: data-kwil-postgres
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    networks:
      - kwil-network

  kwil-node:
    container_name: kwil-node
    hostname: kwil-node
    build:
      context: .
      dockerfile: ./kwil.dockerfile
      # Uncomment the following lines to enable debugging with delve
#      args:
#        - DEBUG_PORT=2345
    ports:
      - "8080:8080"
      - "2345:2345"
    depends_on:
      kwil-postgres:
        condition: service_healthy
    volumes:
      - ./examples/single-node/config.toml:/root/.kwild/config.toml:ro
      - ./examples/single-node/genesis.json:/root/.kwild/genesis.json
      - ./examples/single-node/private_key:/root/.kwild/private_key
      - type: volume
        source: data-kwil
        target: /root/.kwild
        volume:
          nocopy: true
    networks:
      - kwil-network

  logstore-node:
    container_name: logstore-node
    hostname: logstore-node
    image: "ghcr.io/usherlabs/logstore-node:develop"
    command: [ "start-in-docker", "start" ]
    networks:
      - kwil-network
    ports:
      - '7773:7773'
    environment:
        - PROVER_MODE=dev
        - NOTARY_URL=10.200.10.1:7047
        - EXPERIMENTAL_SOROBAN_SINK=true
        - SINK_STELLAR_WALLET_PRIVATE_KEY=SCMDRX7A7OVRPAGXLUVRNIYTWBLCS54OV7UH2TF5URSG4B4JQMUADCYU
    volumes:
      - type: bind
        source: ./examples/logstore-config.json
        target: /home/node/.logstore/config/default.json
        read_only: true
      - type: bind
        source: logstore-data
        target: /home/node/.logstore/

networks:
  kwil-network:
    driver: bridge

volumes:
  data-kwil:
  data-kwil-postgres:
  data-push-tsn-data:
  logstore-data:
