version: "3"

tasks:
  default:
    cmds:
      - task -l

  build:
    desc: Build kwild binary
    cmds:
      - go build -o ./.build/kwild ./cmd/kwild/main.go

  build:debug:
    desc: Build kwild binary with debug flags
    cmds:
      - go build -gcflags "all=-N -l" -o ./.build/kwild ./cmd/kwild/main.go

  tools:
    desc: Install tools
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
      - go install github.com/vektra/mockery/v2@v2.42.1

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  kwil-binaries:
    cmds:
      - ./scripts/kwil_binaries.sh

  clear-data:
    cmds:
      - rm -r ~/.kwild || true


